-- Import existing Design rubric data into Supabase
-- This creates the initial data from your CSV files

-- Product Designer (PD) rubrics
INSERT INTO public.rubric_data (discipline, level, stage, competency, score_1, score_2, score_3, score_4) VALUES
('Design', 'Product Designer', 'Portfolio', 'Craft & Visual Design:', '• Designs are outdated, inconsistent, or low-quality. • Layouts are cluttered, typography and color are weak, and interactive elements are non-functional or missing. • Portfolio is poorly organized or unprofessional.', '• Visual execution is inconsistent. • Layout and hierarchy feel uneven; prototypes or animations are rough. • Portfolio is functional but carelessly presented, with at least 3 projects from the last 6 years and coverage of both desktop and mobile designs.', '• Portfolio is professional. • Visual craft is strong, with polished animations, prototypes, and videos demonstrating good taste. • Includes multiple projects, both professional and personal, reflecting a variety of design experience.', '• Portfolio portrays a highly proactive and versatile designer. • Beyond excellent visual craft, the work demonstrates a curiosity to learn and experiment—incorporating motion, new tools, or varied styles. • Projects show a "builder mindset," where the designer pushes beyond the basic brief to elevate the final product feel through high-fidelity prototyping and creative exploration.'),
('Design', 'Product Designer', 'Portfolio', 'Product Sense & Strategy:', '• Shows little or no understanding of business context. • Problem is unclear. • Design decisions are disconnected from business goals. • Impact is vague or unsupported.', '• Shows some awareness of business context, but connections to outcomes are weak or inconsistent. • Projects tackle a small surface with limited revenue or impact. • Problem and business goals are partially defined, and impact is mentioned but not validated.', '• Clear understanding of the problem and business context for the assigned scope. • Design decisions are visibly connected to the stated goals. • The portfolio includes basic success metrics (quantitative or qualitative) or user feedback to validate the work.', '• Demonstrates strong product thinking. • The designer connects their specific feature work to broader business objectives or metrics (e.g., retention, conversion). • Shows initiative by referencing competitor analysis or data to justify decisions, proving they look beyond the immediate ticket.'),
('Design', 'Product Designer', 'Portfolio', 'Communication', '• Builds the foundation. • Communication is unclear or incomplete. • Explanations are missing or vague. • Design decisions are not justified. • Writing is poor, and hard to navigate.', '• Communication shows some structure but lacks depth or consistency. • Explanations are partial or overly wordy, suggesting excessive reliance on AI-generated text.', '• Communication is structured and logical. • Case studies follow a clear narrative arc (e.g., Problem → Solution →Result) without unnecessary fluff. • Explanations of why decisions were made are present. • May include a walkthrough video or clear visual summaries to aid understanding.', '• Communication is engaging and dynamic. • The designer moves beyond static text, proactively using formats like short video walkthroughs, GIFs, or interactive demos to simulate the final experience. • The narrative clearly articulates the "why" behind decisions, demonstrating a deep ownership of the project from start to finish.'),
('Design', 'Product Designer', 'Portfolio', 'User-centered problem solving', '• Little to no evidence of user-centered thinking. • Problem is unclear. • Process steps and validation are missing. • Edge cases are ignored. • Artifacts such as screenshots of post-its or FigJam boards are unreadable or pixelated.', '• Basic awareness of UX process. • Problem and user context are partially defined. • Research is synthesized to highlight main issues, with some validation of the problem. • Process steps are described superficially.', '• Demonstrates structured user-centered problem-solving. • Problem is clearly defined. • The problem is clearly defined, and solutions are grounded in user research or testing. • The process shows a logical progression (exploration,selection,validation). • Design artifacts are clean, readable, and relevant to the story.', '• Detailed execution. • Research is synthesized into actionable insights rather than just listed. • The solution considers technical constraints, edge cases, and error states, not just the "happy path." • Shows a willingness to iterate based on feedback and challenges assumptions proactively.'),
('Design', 'Product Designer', 'Talent interview', 'Experience and background', '• No product design experience at all; only graphic, marketing, academic or conceptual work.', '• Has some product design exposure but only in simple or non-scalable environments; shallow understanding of real product constraints.', '• Has real product design experience with ownership of small features; understands user flows and delivers work with guidance.', '• Has solid product experience for a mid-level; shows strong fundamentals and has worked on multiple features in real environments with increasing independence.'),
('Design', 'Product Designer', 'Talent interview', 'Product Sense & Strategy:', '• No ability to identify tradeoffs; decisions are arbitrary; lacks understanding of product goals.', '• Understands strategy only when clearly explained; struggles to challenge assumptions or propose alternatives.', '• Understands product goals, frames problems, proposes rational solutions, and evaluates tradeoffs effectively.', '• Exhibits Staff-level product intuition; consistently anticipates product risks, identifies opportunities, and improves strategy.'),
('Design', 'Product Designer', 'Talent interview', 'Collaboration', '• Struggles working cross-functionally; creates misalignment; cannot negotiate feasibility.', '• Collaborates inconsistently; communication is reactive; struggles with engineering tradeoffs.', '• Collaborates smoothly and independently with PMs and engineers; negotiates tradeoffs and helps maintain alignment.', '• Drives strong collaboration; becomes a go-to partner for PMs/Eng; resolves team tensions and increases clarity.'),
('Design', 'Product Designer', 'Talent interview', 'Communication', '• Communication unclear or confusing; cannot present design decisions effectively.', '• Some clarity but lacks structure, depth, or conciseness; struggles with exec or stakeholder conversations.', '• Presents design clearly and persuasively to stakeholders; documents decisions and argues tradeoffs effectively.', '• Craftsmanship-level communicator: clear, concise, persuasive; strong storyteller; could influence leadership.'),
('Design', 'Product Designer', 'Talent interview', 'Ownership & Drive', '• Relies on heavy supervision; avoids ambiguity; cannot handle entire scopes alone.', '• Can own tasks but not projects; struggles when problems are ambiguous; inconsistent accountability.', '• Fully owns feature scopes end-to-end; handles ambiguity; ensures quality; drives outcomes independently.', '• Shows Staff-level ownership: initiates improvements, drives cross-team alignment, creates clarity in ambiguous spaces.'),
('Design', 'Product Designer', 'Hiring manager', 'Communication', '• Cannot articulate growth areas. No clear inspiration sources. Self-assessment disconnected from reality or wildly inaccurate.', '• Identifies 1-2 growth areas but remains vague. Limited inspiration sources (follows a few designers on social media). Generic role models without specific learnings.', '• Honest self-assessment that matches interview performance. Multiple inspiration sources (books, podcasts, conferences). Can connect specific learnings to their work. Has personal projects or side work showing curiosity.', '• Exceptional self-awareness with nuanced reflection. Proactively seeks diverse inspiration across design and adjacent fields. Personal projects demonstrate experimentation. Can trace their design philosophy evolution over time.'),
('Design', 'Product Designer', 'Hiring manager', 'Collaboration', '• Generic interest in Deel ("fast-growing company"). Panics under pressure. Cannot articulate how to handle multiple at-risk projects. Blames external factors for past failures.', '• Some research on Deel but surface-level. When stressed, defaults to working longer hours without strategy. Knows to cut scope but does it arbitrarily without involving the team.', '• Researched Deel''s culture, product, and recent news. Under pressure: knows when to cut scope, when to reach out to manager, how to skim feedback and prioritize with PM/Eng/stakeholders. Flexible about extra effort when needed. Asks for another designer when appropriate.', '• Deep understanding of Deel''s mission and how their skills contribute. Has creative solutions for tight deadlines (phased delivery, MVP approaches, parallel workstreams). Knows exactly when to escalate and what to ask for. Never trenches—always explores options first.'),
('Design', 'Product Designer', 'Hiring manager', 'Ownership & Drive', '• No clear process for tight deadlines. Would freeze if solution was wrong near deadline. Rigid about work-life balance without nuance. Cannot articulate contribution beyond design tasks.', '• Has a process but it''s generic. Would flag wrong solution but unclear on next steps. Understands flexibility needed but uncomfortable with it. Generic answer about team contribution.', '• Clear process for tight deadlines (rapid scoping, stakeholder alignment, focused execution). If solution is wrong: immediately flags, proposes alternatives, rallies team. Understands work-life choice—flexible when needed, sets boundaries when appropriate. Knows what they love (UI, prototyping, data, specific problem types). Has a vision of who they are as a designer.', '• Turns 2-day deadline into a strength—knows exactly what to cut and what''s essential. Wrong solution? Already has backup thinking. Articulates work-life philosophy thoughtfully. Clear vision of their designer identity and trajectory. Genuinely excited about team opportunities and can articulate preferences clearly.')
ON CONFLICT (discipline, level, stage, competency) DO UPDATE SET
  score_1 = EXCLUDED.score_1,
  score_2 = EXCLUDED.score_2,
  score_3 = EXCLUDED.score_3,
  score_4 = EXCLUDED.score_4;

-- Add some Design questions
INSERT INTO public.questions (discipline, stage, competency, question) VALUES
('Design', 'Hiring manager', 'Communication', '• On a scale of 1 to 10, how would you rate your performance in the case study interview and why?
• Beyond the skills we saw in the case study, what are three specific areas you are actively working to improve in as a designer?
• What are your sources of inspiration, and how do you incorporate them into your work?
• Do you have any role models in the design industry? What do you admire about their work or approach?'),
('Design', 'Hiring manager', 'Collaboration', '• Why are you interested in joining Deel specifically? What do you know about our company culture?
• Can you describe a time you had to work on a high-priority, last-minute project for a valued customer? Walk me through what you did and why.
• How do you feel about working hard to deliver projects that are at risk of not meeting their deadline? Can you give me an example of how you''ve handled this in the past?
• Imagine you have five projects, all at risk of not being delivered on time. How would you approach this situation? How would your strategy change if you had six projects at risk?
• Let''s say you''re a product designer with a lot of incoming feedback on a piece of work, and you don''t think you can address it all by the deadline. What''s your process for prioritizing and communicating this?'),
('Design', 'Hiring manager', 'Ownership & Drive', '• How would you approach a two-day deadline to achieve a complex goal? Walk me through your process.
• You''re three days away from a deadline, and you''ve just realized the proposed solution is completely wrong. What are your immediate next steps?
• In a fast-paced environment, do you prefer "work-life balance" or "work-life choice," and what''s the difference to you?
• Beyond your design tasks, what else do you believe a product designer should be doing to contribute to a team''s success?')
ON CONFLICT (discipline, stage, competency) DO UPDATE SET
  question = EXCLUDED.question;

-- Verify the data was inserted
SELECT COUNT(*) as rubric_count FROM public.rubric_data;
SELECT COUNT(*) as question_count FROM public.questions;
